### PR TITLE
missing rescue variable, slow down when state file opening failed.

### PR DESCRIPTION
**Pull request by chaeyk**
minor fixes... :)

### CODE REVIEW

**Comment by sampointer** [comment]
Hey. I've been waylaid by some functionality I've had to add for one of my clients. I shall begin testing your changes in master next week, get a couple of tens of millions of records through it on one of my infrastructures and then we should be good for a full release.

**Comment by sampointer** [comment]
Hey. I've merged the 0.5.x and 0.6.x branches in and completed the conflict resolution. If you could submit a PR to change the documentation to explain how the `api_interval` value is now used I would be happy to push 1.0.0.

**Comment by chaeyk** [comment]
I'm using api_interval as delay of error condition.  There is a mismatch with name and functionality. But I didn't change name to maintain compatibility.

**Comment by chaeyk** [comment]
You'd better update document since my English is not good enough to write a formal document. Or you can change name, maintainer is you. :)

**Comment by sampointer** [comment]
Great. Leave it with me and I'll have 1.0.0 out today

**Pull request merged**
